import type { Trip } from '../types/trip';

export const sampleTrips: Trip[] = [
  {
    id: '1',
    title: '도쿄 벚꽃 여행',
    destination: '도쿄, 일본',
    status: 'completed',
    startDate: '2025-03-15',
    endDate: '2025-03-20',
    coverImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&h=400&fit=crop',
    memo: '벚꽃 시즌 최고였다! 날씨도 완벽했고 라멘이 정말 맛있었다.',
    expenses: [
      { category: 'flight', amount: 350000, label: '인천-나리타 왕복' },
      { category: 'hotel', amount: 400000, label: '신주쿠 호텔 5박' },
      { category: 'food', amount: 200000, label: '식비' },
      { category: 'transport', amount: 80000, label: '교통패스 + 택시' },
      { category: 'activity', amount: 50000, label: '입장료' },
      { category: 'other', amount: 120000, label: '쇼핑 + 기념품' },
    ],
    itinerary: [
      { day: 1, title: '시부야 & 하라주쿠', description: '시부야 스카이 전망대 → 하라주쿠 거리 → 메이지 신궁' },
      { day: 2, title: '아사쿠사 & 스카이트리', description: '센소지 → 나카미세도리 → 스카이트리 전망대' },
      { day: 3, title: '신주쿠 & 골든가이', description: '신주쿠 교엔 벚꽃 → 가부키초 → 골든가이 이자카야' },
      { day: 4, title: '카마쿠라 당일치기', description: '에노시마 → 대불상 → 해변 산책' },
      { day: 5, title: '아키하바라 & 긴자', description: '아키하바라 전자상가 → 긴자 쇼핑 → 츠키지 시장' },
      { day: 6, title: '출국', description: '호텔 체크아웃 → 나리타 공항' },
    ],
    photos: [],
    places: [],
    checklist: [],
    createdAt: '2025-03-25T00:00:00Z',
    updatedAt: '2025-03-25T00:00:00Z',
  },
  {
    id: '2',
    title: '방콕 맛집 투어',
    destination: '방콕, 태국',
    status: 'completed',
    startDate: '2025-01-10',
    endDate: '2025-01-14',
    coverImage: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600&h=400&fit=crop',
    memo: '길거리 음식 천국! 팟타이랑 망고 스티키 라이스 잊을 수 없다.',
    expenses: [
      { category: 'flight', amount: 280000, label: '인천-수완나폼 왕복' },
      { category: 'hotel', amount: 200000, label: '카오산로드 근처 호텔 4박' },
      { category: 'food', amount: 100000, label: '식비 (길거리 음식 포함)' },
      { category: 'transport', amount: 40000, label: '툭툭 + BTS' },
      { category: 'activity', amount: 30000, label: '왕궁 + 사원 입장료' },
    ],
    itinerary: [
      { day: 1, title: '왕궁 & 왓포', description: '왕궁 → 왓포 (와불) → 차오프라야 강 페리' },
      { day: 2, title: '짜뚜짝 & 쇼핑', description: '짜뚜짝 주말시장 → 시암 파라곤 → 아시아티크' },
      { day: 3, title: '맛집 투어', description: '미슐랭 길거리 음식 → 쏨탐 → 팟타이 → 망고 스티키 라이스' },
      { day: 4, title: '수상시장 & 출국', description: '담넌사두악 수상시장 → 공항' },
    ],
    photos: [],
    places: [],
    checklist: [],
    createdAt: '2025-01-20T00:00:00Z',
    updatedAt: '2025-01-20T00:00:00Z',
  },
  {
    id: '3',
    title: '로마 & 피렌체 여행',
    destination: '로마/피렌체, 이탈리아',
    status: 'planned',
    startDate: '2026-06-10',
    endDate: '2026-06-17',
    coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&h=400&fit=crop',
    memo: '',
    expenses: [
      { category: 'flight', amount: 800000, label: '인천-로마 왕복' },
      { category: 'hotel', amount: 700000, label: '로마 4박 + 피렌체 3박' },
      { category: 'food', amount: 400000, label: '예상 식비' },
      { category: 'transport', amount: 100000, label: '기차 + 시내교통' },
      { category: 'activity', amount: 150000, label: '입장료 + 투어' },
    ],
    itinerary: [],
    photos: [],
    places: [
      { name: '콜로세움', priority: 'must', note: '오전 일찍 가야 줄이 짧다' },
      { name: '바티칸 미술관', priority: 'must', note: '온라인 예매 필수' },
      { name: '트레비 분수', priority: 'must', note: '야경이 예쁘다고 함' },
      { name: '판테온', priority: 'must', note: '무료 입장' },
      { name: '우피치 미술관', priority: 'must', note: '피렌체 필수' },
      { name: '두오모', priority: 'want', note: '피렌체 대성당 꼭대기 전망' },
      { name: '트라스테베레', priority: 'want', note: '로마 현지인 동네, 맛집 많음' },
    ],
    checklist: [
      { text: '여권 유효기간 확인', checked: true },
      { text: '항공편 예약', checked: false },
      { text: '숙소 예약', checked: false },
      { text: '여행자 보험 가입', checked: false },
      { text: '유레일 패스 알아보기', checked: false },
      { text: '바티칸 미술관 온라인 예매', checked: false },
    ],
    createdAt: '2025-12-01T00:00:00Z',
    updatedAt: '2025-12-01T00:00:00Z',
  },
  {
    id: '4',
    title: '제주도 힐링 여행',
    destination: '제주도, 한국',
    status: 'planned',
    startDate: '2026-04-01',
    endDate: '2026-04-04',
    coverImage: 'https://images.unsplash.com/photo-1579169326371-b4f4757e3485?w=600&h=400&fit=crop',
    memo: '',
    expenses: [
      { category: 'flight', amount: 120000, label: '김포-제주 왕복' },
      { category: 'hotel', amount: 250000, label: '애월 펜션 3박' },
      { category: 'food', amount: 150000, label: '예상 식비' },
      { category: 'transport', amount: 100000, label: '렌터카' },
    ],
    itinerary: [],
    photos: [],
    places: [
      { name: '성산일출봉', priority: 'must', note: '일출 보기' },
      { name: '만장굴', priority: 'want', note: '용암 동굴 체험' },
      { name: '우도', priority: 'want', note: '자전거 투어' },
      { name: '협재 해수욕장', priority: 'want', note: '에메랄드빛 바다' },
      { name: '카페거리 (애월)', priority: 'maybe', note: '오션뷰 카페' },
    ],
    checklist: [
      { text: '항공편 예약', checked: false },
      { text: '렌터카 예약', checked: false },
      { text: '숙소 예약', checked: false },
      { text: '맛집 리스트 정리', checked: false },
    ],
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-01-15T00:00:00Z',
  },
];
